platform :ios, '9.3'

plugin 'cocoapods-fix-react-native'

target 'ViroSample' do
  use_frameworks!

  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'	

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTActionSheet',
        'RCTGeolocation',
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket',
        'RCTNetwork',
        'RCTVibration',
        'RCTSettings',
        'RCTAnimation',
        'RCTLinkingIOS',
        'RCTImage',
    ]

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'react-native-maps', path: '../node_modules/react-native-maps'

end

# When using RN in combination with Cocoapods, a lot of 
# things are broken. These are the fixes we had to append 
# to our Podfile when upgrading to ReactNative@0.55.3.
# 
# WARNING: Check those line numbers when you're on a different version!

def change_lines_in_file(file_path, &change)
  print "Fixing #{file_path}...\n"

  contents = []

  file = File.open(file_path, 'r')
  file.each_line do | line |
    contents << line
  end
  file.close

  File.open(file_path, 'w') do |f|
    f.puts(change.call(contents))
  end
end

post_install do |installer|
  # https://github.com/facebook/yoga/issues/711#issuecomment-381098373
  change_lines_in_file('./Pods/Target Support Files/yoga/yoga-umbrella.h') do |lines|
    lines.reject do | line |
      [
        '#import "Utils.h"',
        '#import "YGLayout.h"',
        '#import "YGNode.h"',
        '#import "YGNodePrint.h"',
        '#import "YGStyle.h"',
        '#import "Yoga-internal.h"',
      ].include?(line.strip)
    end
  end
end
